### ISSUE TITLE
Implement healthcheck

### ISSUE THREAD

**Issue by ir4y** [Aidbox/Issues#473]
## Problem I need to solve
In some scenarios like integrational unit testing, it is needed that server is healthy before proceeding with the next step.

## Solution I see
Add health check in to aidbox Dockerfile https://docs.docker.com/engine/reference/builder/#healthcheck

**Comment by ruscoder** [comment]
Aidbox already has it. 

```
get /__healthcheck
```

**Comment by ir4y** [comment]
This issue is about using this health check in Dockerfile https://docs.docker.com/engine/reference/builder/#healthcheck

**Comment by octoshikari** [comment]
@ir4y Hello. It is not possible to add HEALTHCHECK command into aidbox docker image, because it doesn't support using environment variables, I mean AIDBOX_PORT. As a result, if you will set up custom port - not 8080, we cannot dynamically change port for healthcheck. Possible solution for that run waiting script before start you're testing or extends image by your custom healthcheck command depends on your AIDBOX_PORT

```dockerfile
FROM healthsamurai/devbox

EXPOSE 8888

HEALTHCHECK --interval=30s --retries=2 \
  CMD curl -f http://localhost:8888/__healthcheck || exit 1


```
