### ISSUE TITLE
[BUG] Nested Qustionnaire.item is not validating by zen

### ISSUE THREAD

**Issue by ir4y** [Aidbox/Issues#545]
**Describe the bug**
Nested Qustionnaire.item is not validating by zen, I can pass any data to it.
The schema for it is missing.

**Severity**
Critical

<img width="990" alt="Screenshot 2022-10-19 at 17 21 39" src="https://user-images.githubusercontent.com/1488983/196703411-5c5b34ba-6d44-477e-9f72-6ab15f23c379.png">

**Comment by VarvaraSemenova** [comment]
@ir4y thank you for reporting, we'll fix asap

**Comment by ghost** [comment]
@ir4y
You are right, the issue was with schemas not being generated for `contentReference`s. We fixed schemas generation in [zen-lang/fhir](https://github.com/zen-lang/fhir) so that this is no longer the case.
Please check out the latest [0.5.25-1](https://github.com/zen-lang/fhir/releases/tag/0.5.25-1) release and let us know if something is missing.

**Comment by ir4y** [comment]
@islambegk It worked. Thank you.
